### ISSUE TITLE
Port setting

### ISSUE THREAD

**Issue by davidbwaters** [xfiveco/generator-chisel#143]
Hi, it would be nice to be able to specify a port for when running the generator. Thanks.

**Comment by thymikee** [comment]
Hi @davidbwaters, thanks for bringing that up.

We're trying to use minimum setup steps possible while generating project just to not frustrate most of our users. And setting up different default port was never an issue, because BrowserSync we use to serve the page handles used ports and adjust this automatically. 

You can always override this behaviour in `gulp/tasks/serve` and add `port: XXXX` to `browserSyncConfig` object. I know this may not be ideal for you, but it's possible

**Comment by davidbwaters** [comment]
Hey, I was referring to setting up the Wordpress port setting for connecting to the DB.  Would be nice if the generator had those filled with defaults and you could just confirm through them if needed.  As it is now, the install can't progress without the default ports.

**Comment by thymikee** [comment]
Oh, this makes more sense! Are you willing to post a PR with the feature? 🙂

**Comment by luboskmetko** [comment]
This is done and will be in the next release.
