### ISSUE TITLE
 Allow to select from two ITCSS versions - full and minimal

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#147]
- full - what we have currently in master
- minimal - just reset, setup & mixins

@thymikee can you please list which files exactly you'd like to keep in minimal ITCSS version?

**Comment by thymikee** [comment]
In _minimal_ version I'd like to have only:
* whole `generic` excluding `_reset.scss` (resetting should be handled by `normalize.css`)
* whole `tools`
* whole `settings`
* `objects` with `_wrapper.scss` only
* `utilities` excluding `_spacing.scss` (ideally I'd like to have it all in one file, because it will be small enough; too many micro-files is really annoying to find the right one tbh)
* `components` with `_header.scss` and `_footer.scss` only (btw, I like a button to be an object, so it can be overwritten by components)
* `elements` with `_html.scss` only
