### ISSUE TITLE
Adjust table object styling?

### ISSUE THREAD

**Issue by marcinkrzeminski** [xfiveco/generator-chisel#158]
Hi,

I have noticed while doing some internal reviews that inside generic/_tables.scss we have this code

```
table {
  width: 100%; /* [1] */
}
```

In addition we also have a objects/_table.scss with a code like this

```
.o-table {
  width: 100%;
}
```

Does it make sense to keep the "o-table"? in the codebase?

**Comment by luboskmetko** [comment]
Thanks, Marcin. This is taken from https://github.com/inuitcss/inuitcss. Although, they have a few size variants for the table object yet.

I think it still makes sense to keep this object because someone can decide they don't want the default tables styling to be `width: 100%;` so they can delete the element but still use the object when needed.

**Comment by marcinkrzeminski** [comment]
OK, I understand. I think it depends on the developer approach. Some devs prefer to use defaults while the others a different way to go ;).
