### ISSUE TITLE
Failed to copy `src` dir for WP projects

### ISSUE THREAD

**Issue by thymikee** [xfiveco/generator-chisel#167]
Copying `src` directory for WP generated projects results in results in this error, while selecting `Where do you want to place the 'src' folder` option:
```
{ Error: EEXIST: file already exists, link '/Users/thymikee/Projects/test-chisel/src' -> '/Users/thymikee/Projects/test-chisel/wp/wp-content/themes/test-chisel/src/'
  errno: -17,
  code: 'EEXIST',
  syscall: 'link',
  path: '/Users/thymikee/Projects/test-chisel/src',
  dest: '/Users/thymikee/Projects/test-chisel/wp/wp-content/themes/test-chisel/src/' }
```

or this one:
```
{ Error: ENOENT: no such file or directory, link '/Users/thymikee/Projects/test-chisel/src' -> '/Users/thymikee/Projects/test-chisel/wp/wp-content/themes/test-chisel/src/'
  errno: -2,
  code: 'ENOENT',
  syscall: 'link',
  path: '/Users/thymikee/Projects/test-chisel/src',
  dest: '/Users/thymikee/Projects/test-chisel/wp/wp-content/themes/test-chisel/src/' }
```

@jakub300 spotted it and I can repro on my machine.

**Comment by luboskmetko** [comment]
You mean this happens when _Where do you want to place the 'src' folder: WordPress theme folder_ is selected? 

It works for me on Windows so maybe a permissions issue on Mac? I had to use [fs-extra](https://github.com/jprichardson/node-fs-extra/) for moving the folder [here](https://github.com/xfiveco/generator-chisel/blob/master/generators/wp/index.js#L124) because default methods didn't work.

I appreciate if you can investigate this further and rewrite if necessary. Thanks

**Comment by thymikee** [comment]
Not a chance it's a permission issue. I'll try to investigate some time later
