### ISSUE TITLE
Browsersync notification - helpful or annoying? 

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#186]
@thymikee @arturkot @jakub300 shouldn't we switch this off by default and document how it can be switched on?

**Comment by jakub300** [comment]
Not a problem for me

**Comment by luboskmetko** [comment]
Ok, let's keep it like it is and I'll document how to switch it off.

**Comment by arturkot** [comment]
A bit offtopic: auto opening `index.html` in browser has always been annoying for me. Usually I was looking for a way to disable it.

It's probably because:

* I quite often play around with gulp/npm and have to restart the server.
* In iTerm I can command click on links which opens a project straight from a command line _when_ I want it.

**Comment by luboskmetko** [comment]
@arturkot that's this one https://browsersync.io/docs/options#option-open, right? I would document it as well
