### ISSUE TITLE
Switch to babel-preset-env

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#260]
https://github.com/babel/babel-preset-env

This is recommend by Babel itself during installation of our current `babel-preset-es2015`

**Comment by jakub300** [comment]
I spent some time testing it today and I recommend waiting until [babel v7](http://babeljs.io/blog/2017/09/12/planning-for-7.0) is released. Reasons:
* we will not benefit from browsers list based transforms anyway because we need them all to be compatible with uglifyjs,
* in v7 `babel-preset-env` will make it possible to share `browserslist` config with autoprefixer, they must be defined separately now,
* in v7 we may use automatic polyfilling for things like `Promises`, `Array.from` etc., that is not possible in current version.

**Comment by jakub300** [comment]
Hey, unfortunately not. in the near future. Update to eslint-config-chisel was to match parser version used by eslint and chisel. I have WiP branch with update in the office. I will push it tomorrow.
