### ISSUE TITLE
ITCSS improvements (on WP projects too)

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#28]
- objects library (#84)
- sample components
- component generator (should be a separate issue)
- etc.

**Comment by thymikee** [comment]
Apart from above, I'd like to adjust our current ITCSS structure.

- [ ] Move `normalize` to `generic/` dir
- [ ] Make clearfix a mixin instead of placeholder beacuse of [known problems](https://www.sitepoint.com/avoid-sass-extend/)
- [ ] Remove `c-` prefix from components classnames. We're using prefixes for `o-objects` and `u-utilities/trumps`. In this CSS architecture these are _special_ classes with special functions – `objects` for reusability and providing a base for other styles and `trumps` overriding everything else. On the other hand `components` are just regular UI classes we're using most of the time, so why bother adding extra clutter to their naming. This would imply that any class without a prefix is a component.
- [ ] Use BEM naming. Add `.footer__list` and `.footer__list-item` to `_footer.scss` component plus couple of extra components. Developers are more likely to follow a given pattern if there is such, so we need to provide good foundation :)

**Comment by luboskmetko** [comment]
Sounds good! 

One thing - how would you move `normalize` to `generic` if normalize is installed via npm?

**Comment by thymikee** [comment]
Maybe there's an issue I'm not aware of, but doing 
```
/* generic/_reset.scss */
@import 'normalize-scss/sass/normalize/import-now';
```
inside e.g. `generic/_reset.scss` works for me, as it's just an import from node_modules.

**Comment by luboskmetko** [comment]
Ok, thanks

**Comment by danekszy** [comment]
Hey guys.
@thymikee All suggestions look good to me except No. 3...
I wouldn't drop the `c-` prefix for classes, since doing so would make it less obvious whether (the previous) developer followed the guidelines or not. This way I wouldn't be able to tell if something is a component class, or some deviation from our recommended style (or even some 3rd party vendor stuff).

**Comment by luboskmetko** [comment]
I had doubts about no. 3 as well, I would rather stick to the convention. On the other hand, if writing `c-` over and over would bother developers or make them sick of ITCSS, we could allow this small departure from the standard or let developers decide ("Components' class names can be written with .c- prefix or without it...")

**Comment by thymikee** [comment]
Ok, so let's leave it to promote good practices and avoid confusion for newcomers.

**Comment by arturkot** [comment]
Just wanted to write I'm glad we decided to keep `c-` prefixes. :)
