### ISSUE TITLE
PNG issue (only windows?)

### ISSUE THREAD

**Issue by Skowryk** [xfiveco/generator-chisel#33]
I've found an issue while adding pngs to a repo and pushing to gitlab.
It treats pngs like a text files and probably alters their eol.
If you add *.png binary to .gitattributes, problem is solved.

**Comment by luboskmetko** [comment]
Thanks for the report. Indeed this was an issue but it should be already fixed in the latest release https://github.com/xfiveco/generator-chisel/releases/tag/v0.1.6. Currently we list the text files explicitly https://github.com/xfiveco/generator-chisel/blob/master/generators/app/templates/.gitattributes
