### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#345]
After reading https://www.smashingmagazine.com/2018/02/jquery-vue-javascript/, I was thinking whether it wouldn't be useful to be able to add Vue.js to Chisel projects. Contrary to the article I mean via npm so it integrates with our build process. Not sure if it needs to be a scaffolding option or it can be done after project is setup.

Is there any use case for it? For example in more advanced WP projects with complex front-end?

@jakub300 what you think?

**Comment by jakub300** [comment]
It's hard question. There may be some use for for it in advanced projects but I do not personally recall such projects. Also I'm not really sure what kind of support we are talking about.

If you would like to support [Single File Components](https://vuejs.org/v2/guide/single-file-components.html) that would be problematic because you would have to create CSS extraction as part of CSS bundling (unless you are ok with CSS staing in JS files). If you don't want to do things like that, use of Vue should be just importing and using it.

Personally I would probably consider something lighter like Preact if I would like to do some kind of interactivity like that.

What do you think @arturkot?

**Comment by arturkot** [comment]
I'm more after removing stuff rather than adding it. ;) The thing with Chisel is that it's super easy to add Vue (and anything else) if you _need it_. Most of the time vanilla JS does the job just fine IMHO.

Also, as @jakub300 mentioned - it _really_ depends on the case. Do you need full library/framework? Or, perhaps, something small like Preact or [Moon](http://moonjs.ga).

IMHO it's not worth attaching Chisel to a next library. It's enough we've got jQuery on board (although I'd gladly remove it as well ;->).

**Comment by luboskmetko** [comment]
Thanks, guys. Yes, I was thinking about it like an alternative to jQuery/vanilla JS when you need a bit more interactivity on the page and would like to avoid messing with DOM yourself. 

Preact / Moon look like good such alternatives, I guess it would be enough to add some recipes for how to use them with Chisel. So closing this one.
