### ISSUE TITLE
How to use wp_localize_script in chisel

### ISSUE THREAD

**Issue by rakshans1** [xfiveco/generator-chisel#364]
how to add wp_localize_script without registering new js file

**Comment by luboskmetko** [comment]
@rakshans1 thanks for reaching out. Below is a general idea how to achieve this, however not sure if this is exactly what you want:

You can create a new class in Chisel folder and load it in `functions.php`. In the class, I'm calling helper method `revisionedPath` from `Chisel\Extensions\ChiselTwig`. This should return revision file name of the JS bundle.

_Note: I've put whole example from https://codex.wordpress.org/Function_Reference/wp_localize_script into constructor, normally you'd like to organize your code better._

```php
<?php

namespace Chisel;

use Chisel\Extensions\ChiselTwig;

/**
 * Class Localization
 * @package Chisel
 *
 */
class Localization {
	public function __construct() {

		$chisel_twig = new ChiselTwig;

		// Register the script
		wp_register_script( 'some_handle', $chisel_twig->revisionedPath('scripts/app.bundle.js') );

		// Localize the script with new data
		$translation_array = array(
			'some_string' => __( 'Some string' ),
			'a_value' => '10'
		);

		wp_localize_script( 'some_handle', 'my_object', $translation_array );

		// Enqueued script with localized data.
		wp_enqueue_script( 'some_handle' );
	}
}
```

then for example in `app.js` you could use the data from PHP:

```js
import greet from './modules/greeting';

greet(my_object.some_string);
```

But you also should remove this line `<script src="{{ revisionedPath('scripts/app.bundle.js') }}" defer></script>` from `templates/layouts/base.twig` otherwise the script will be loaded twice. 

Another thing is that while by default the JS bundle has `defer` attribute, this one doesn't

Let us know if it helps.

**Comment by rakshans1** [comment]
Thanks @luboskmetko for explanation.
It works

**Comment by luboskmetko** [comment]
No problem.
