### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by trejster** [xfiveco/generator-chisel#365]
So I've been using chisel to build a custom theme for a client. I have now completed the development however I've hit a stumbling block. The client is using go daddy with wordpress already installed. 

Am I right in thinking she needs a host with chisel/timber installed also in order for the site to run? I think I mistakenly thought the build task would compile to php files for deployment but that doesn't seem to be the case, my templates are still twig files?

**Comment by jakub300** [comment]
Hey @trejster,

Timber is a [WordPress plugin](https://wordpress.org/plugins/timber-library/) that converts twig files to PHP and executes them. Timber is written in PHP and it should generally work on all hostings that allow installation of WordPress plugins. There is nothing Chisel specific (besides installing Timber) that needs to be on the hosting.

Assuming client already has WordPress installed on their hosting (and you don't wan't to overwrite it) the steps would be something like that:
1. On the hosting: install Timber from WordPress plugins directory and enable it.
2. On the hosting: install other plugins required by your theme (for example ACF) if there are any.
3. Locally: run `yarn build` or `npm run build` depending what is your preferred package manager. This will prepare production version of JS and CSS files in the `dist` folder inside of theme folder.
4. If you are using ACF you will need to migrate your fields definitions to hosting, either by manually exporting/importing them or for example using [Local JSON](https://www.advancedcustomfields.com/resources/local-json/).
4. Copy theme folder to hosting.
5. You should see the theme in WordPress, you should be able to preview/enable it.

Regarding converting twig to PHP, it is not possible to do it upfront but you may enable Twig Cache in production that will cache generated php files - this is descried as [Cache the Twig File (but not the data)](https://timber.github.io/docs/guides/performance/#cache-the-twig-file-but-not-the-data) in the Timber documentation. If client is using "Managed WordPress" on GoDaddy this is will have small effect  because hosting already has its own cache.
