### ISSUE TITLE
Problem with wp-cli during installation

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#376]
@jakub300 what could be the reason of the following problem during installation?

![wp-cli](https://user-images.githubusercontent.com/176712/40959016-a92e3f50-689b-11e8-9ceb-201eff2e2a0e.png)

A developer reports it. Is it some permission issue on macOS? Thanks

**Comment by jakub300** [comment]
Weird, I never encountered it. 
First thing would be to check if wp-cli is in that path.
If it is what happens when you try to run `php /path/to/wp-cli.phar --version` in your terminal
It it is not there try to reinstall chisel, this file is inside of the package and should be installed with chisel.

**Comment by luboskmetko** [comment]
Thanks, looks that reinstalling helped in this case.
