### ISSUE TITLE
Base our Stylelint config on external standard

### ISSUE THREAD

**Issue by danekszy** [xfiveco/generator-chisel#47]
Hey,

I'm in the middle of project development for client using Chisel and so far I've been running into many problems with code style.
At one point I even discovered some rules that contradict each other (requiring single quotes and enforcing double quotes on font names at the same time).
Stylelint seems to be really strict (as opposed to scss_lint which has sane defaults).
Perhaps we could consider tweaking our settings or using some external config with few overrides?
Seems like https://github.com/stylelint/stylelint-config-standard is the most popular one right now.

I'd love our linter to nugde me in the right direction, without being too dogmatic at the same time...
Is there a way to define some rules that would warn, but not err?

Curious about your feedback.

D.

**Comment by thymikee** [comment]
I'm not a big fan of strict style linting, to be honest. The only "style" things I care about is using sane amount of whitespace for readability and not using `&` for classname concatenation (except for class modifiers). 

The important things are styling concepts and architecture, and this is where we should put our efforts.

**Comment by luboskmetko** [comment]
Both Stylelint and ESLint configs were just some initial versions and definitely they need to be updated according developers feedback. I've tried to follow our coding standards but it's quite possible some rules are too strict or contradictory. So feel free to update them.

But let's not forget that these code linters give us an opportunity to increase quality of our code much more effectively than by having a written coding standards and doing manual code reviews. So we shouldn't give up on them completely but rather agree on some sane minimum.

**Comment by luboskmetko** [comment]
I see this issue is still opened so I'll post here too. I suggest that we review the current stylint config or compare with stylelint-config-standard and remove rules which are too strict or contradictory.

Then we could sort out the remaining rules according severity and set them to errors or warnings. I would still break the build on errors, but let's say those would be just a few basic rules if we are able to agree on them (like no IDs).

**Comment by thymikee** [comment]
I'd like to have:
* [error] selector-no-id (as we utilise ITCSS)
* [warn] 2 spaces for indentation (sam as in `editorconfig` and `eslint`)
* [warn] max-nesting-depth: 2
* [warn] newlines between class declarations

**Comment by luboskmetko** [comment]
Ok, thanks, so I'll try to set this up and see how it works. I can make all other rules as warnings too and we can remove them if they turn out to be useless.

**Comment by luboskmetko** [comment]
I've just changed the most rules to warnings, so they don't halt the build. Only the following still trigger errors and stop the build:

- length-zero-no-unit: true
- number-leading-zero: always
- property-case: lower
- selector-no-id: true
- unit-case: lower
- value-keyword-case: lower

I've compared our rules to stylelint-config-standard and it seems even more strict than our set. But since we now mostly show warnings it should be fine. If some of those warnings are pointless, let me know and we can remove them completely.

**Comment by thymikee** [comment]
Hm, wouldn't it be better to use extend `stylelint-config-standard` and override some of the rules?
https://github.com/stylelint/stylelint-config-standard#usage

Currently this file is quite big.

**Comment by jakub300** [comment]
Hey Lubos, since commit fcc0e9d we never halt build on error.

**Comment by luboskmetko** [comment]
@thymikee their config doesn't differ in rules severity so it would trigger error on all rules.  I don't think it's usable for what we are up to here - halt build on just a few key rules, show warnings on all other rules - because we would have to override everything. 

@jakub300 it's changed in this commit again, please see discussion above for reasoning

**Comment by thymikee** [comment]
Nah, I thought there would be just a couple of rules to override.

**Comment by luboskmetko** [comment]
I've made the config file more compact by setting default severity to warning, should be easier to maintain.
