### ISSUE TITLE
Browser reloading delayed on templates watch

### ISSUE THREAD

**Issue by luboskmetko** [xfiveco/generator-chisel#77]
@thymikee @jakub300 @danekszy any idea what could be causing this http://screencast.com/t/5MDu7s1veShX? It looks like browser reloads sooner than the templates watch task is finished, so it's like one save behind. Have you encountered it?

**Comment by thymikee** [comment]
Just a wild guess, but I'd double check this line. Not a gulp expert but we
may listen to the end event earlier than necessary, thus BS reloads before
compiling templates. Try to move it at the end of the stream, like it was
before.

19 paź 2016 10:31 "Lubos Kmetko" <notifications@github.com> napisał(a):

@thymikee <https://github.com/thymikee> @jakub300
<https://github.com/jakub300> @danekszy <https://github.com/danekszy> any
idea what could be causing this http://screencast.com/t/5MDu7s1veShX? It
looks like browser reloads sooner than the templates watch task is
finished, so it's like one save behind. Have you encountered it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xfiveco/generator-chisel/issues/77>, or mute the thread

**Comment by jakub300** [comment]
Reload [is part](https://github.com/xfiveco/generator-chisel/blob/fc7fd581c0dbf4479a99cac71aae79761a91ae78/generators/app/templates/gulp/tasks/templates.js#L29) of `templates-watch` task.

But I got report from one developer that on Visual Studio Code when he modifies styles BrowserSync loads old main.css files so we could investigate that too.

**Comment by thymikee** [comment]
https://github.com/xfiveco/generator-chisel/blob/master/generators/app/templates/gulp/tasks/templates.js#L29

19 paź 2016 10:38 "Michał Pierzchała" <thymikee@gmail.com> napisał(a):

**Comment by jakub300** [comment]
Actually that interesting idea.

**Comment by luboskmetko** [comment]
Seems that moving it at the end (after `.pipe(gulp.dest(config.dest.base))`) helped it for now. I'd let you know if I encounter this again. Thanks!

**Comment by danekszy** [comment]
@luboskmetko Hmm, strange... Browsersync is supposed to fire on pipe's `end` event and I put it at the beginning since for some reason, this event didn't fire after the `filter` plugin...

@jakub300 What platform was that developer on? Styles are separate task and they use injection (`sync`) rather than reload.

**Comment by danekszy** [comment]
Tried to reproduce this on windows, but I couldn't...
@luboskmetko Have you checked if this bug occurs with other editors?
Does it happen on top level template, private or both?

**Comment by luboskmetko** [comment]
@danekszy I couldn't either on a freshly generated project from master. The project where it happened was set up a few days ago (so the version before merging the wp branch). But I copied the latest gulp files to it so maybe it's some other stuff in this particular project. I'd let you know if I reproduce it in other project.

**Comment by luboskmetko** [comment]
I'm closing this for now. Will open it again if I encounter it in the newly setup projects.
